import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar"
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PrehledLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="app">
            {children}
            cs
        </div>
    );
}
